menu:
    Blog: /
    Archive: /archives/
    Dimpurr's Blog: http://weibo.com/sunchongsheng
    DIM'ENSIN Blog: https://github.com/pinggod
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2020
