menu:
    NOTED DIM'ENSIONS: /
    Archive: /archives/
    Rss: /atom.xml

menu2:
    Blog: http://blog.dimpurr.com/
    Blog.moe: https://blog.dim.moe/
    Book: http://book.dimpurr.com/
    Book.moe: http://book.dim.moe/
    NOTE: http://note.dimpurr.com/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2020
